config/routes.rb
Rails.application.routes.draw do
  get 'educators/:id/edit' => 'educators#edit'
  root 'parents#index'
  get 'sessions/login'
  post 'sessions/login'
  get 'sessions/logout'

  resources :educators
  resources :parents

end

app/models/educator.rb
class Educator < ActiveRecord::Base
  has_secure_password
end

app/models/parent.rb
class Parent < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/educators_controller.rb
class EducatorsController < ApplicationController
  before_action :set_educator, only: [:show, :edit, :update, :destroy]


  def edit
    @educator = Educator.find_by_id(session[:educator_id])
  end

  def update
    respond_to do |format|
      if @educator.update(educator_params)
        format.html { redirect_to parents_path, notice: 'Educator was successfully updated.' }
        format.json { render :show, status: :ok, location: @educator }
      else
        format.html { render :edit }
        format.json { render json: @educator.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def set_educator
      @educator = Educator.find(params[:id])
    end

    def educator_params
      params.require(:educator).permit(:name, :email, :password)
    end

end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_action :logged_in?
  before_action :set_parent, only: [:show, :edit, :update, :destroy]

  # GET /parents
  # GET /parents.json
  def index
    @parents = Parent.all
    @list_by_educator = Parent.where(educator_id: session[:educator_id])
  end

  # GET /parents/1
  # GET /parents/1.json
  def show
  end

  # GET /parents/new
  def new
    @parent = Parent.new
  end

  # GET /parents/1/edit
  def edit
  end

  # POST /parents
  # POST /parents.json
  def create
    @parent = Parent.new(parent_params)

    respond_to do |format|
      if @parent.save
        format.html { redirect_to @parent, notice: 'Parent was successfully created.' }
        format.json { render :show, status: :created, location: @parent }
      else
        format.html { render :new }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parents/1
  # PATCH/PUT /parents/1.json
  def update
    respond_to do |format|
      if @parent.update(parent_params)
        format.html { redirect_to @parent, notice: 'Parent was successfully updated.' }
        format.json { render :show, status: :ok, location: @parent }
      else
        format.html { render :edit }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parents/1
  # DELETE /parents/1.json
  def destroy
    @parent.destroy
    respond_to do |format|
      format.html { redirect_to parents_url, notice: 'Parent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parent
      @parent = Parent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parent_params
      params.require(:parent).permit(:student_name, :parent_name, :parent_email, :educator_id)
    end


    def logged_in?
      if Educator.find_by_id(session[:educator_id])

			else
				redirect_to sessions_login_path, notice: 'Message Here, no dice'
			end

    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
  	if request.post?
  	  educator = Educator.find_by_email(params[:email])
  	  if educator && educator.authenticate(params[:password])
  		  session[:educator_id] = educator.id
  		  redirect_to parents_path, notice: 'You have logged in!'
  	  else
  		flash[:notice] = 'Login Failed'
      end
    end
  end


  def logout
    session[:user_id]
    redirect_to sessions_login_path, notice: "You have logged out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/educators_helper.rb
module EducatorsHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/educators/_form.html.erb
<%= form_for(@educator) do |f| %>
  <% if @educator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@educator.errors.count, "error") %> prohibited this educator from being saved:</h2>

      <ul>
      <% @educator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>


  <!-- <div class="field">
    <%= f.hidden_field :educator_id, :value => session[:educator_id] %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/educators/edit.html.erb
<h1>Editing Educator</h1>

<%= render 'form' %>

<%= link_to 'Show', @educator %> |
<%= link_to 'Back', parents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teacher</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>

</body>
</html>

app/views/parents/_form.html.erb
<%= form_for(@parent) do |f| %>
  <% if @parent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parent.errors.count, "error") %> prohibited this parent from being saved:</h2>

      <ul>
      <% @parent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_name %><br>
    <%= f.text_field :student_name %>
  </div>
  <div class="field">
    <%= f.label :parent_name %><br>
    <%= f.text_field :parent_name %>
  </div>
  <div class="field">
    <%= f.label :parent_email %><br>
    <%= f.text_field :parent_email %>
  </div>

  <div class="field">
    <%= f.hidden_field :educator_id, :value => params[:educator_id] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parents/edit.html.erb
<h1>Editing Parent</h1>

<%= render 'form' %>

<%= link_to 'Show', @parent %> |
<%= link_to 'Back', parents_path %>

app/views/parents/index.html.erb
<p id="notice"><%= notice %></p>
<header class="the_head">
<span class="educator_options">
  <%= link_to "Logout", sessions_logout_path  %> |
  <%= link_to "Edit Educator", edit_educator_path(session[:educator_id])   %>
</span>
  <% if session[:educator_id] %>
    <div>Hello <%= Educator.find_by_id(session[:educator_id]).name %></div></br>
  <% end %>

</header>
<h1 class="box">Listing Parents</h1>

<%= link_to 'New Parent', new_parent_path %>

<% %>
  <table>
    <thead>
      <tr>
        <th>Student name</th>
        <th>Parent name</th>
        <th colspan="2">Parent email</th>
        <th class="tablehead" colspan="3"> Table Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @list_by_educator.each do |parent| %>
        <tr>
          <div class="table_main">
            <td><%= parent.student_name %></td>
            <td><%= parent.parent_name %></td>
            <td colspan="2"><%= parent.parent_email %></td>
          </div>
          <td><%= link_to 'Show', parent %></td>
          <td><%= link_to 'Edit', edit_parent_path(parent) %></td>
          <td><%= link_to 'Destroy', parent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<br>

app/views/parents/new.html.erb
<h1>New Parent</h1>

<%= render 'form' %>

<%= link_to 'Back', parents_path %>

app/views/parents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student name:</strong>
  <%= @parent.student_name %>
</p>

<p>
  <strong>Parent name:</strong>
  <%= @parent.parent_name %>
</p>

<p>
  <strong>Parent email:</strong>
  <%= @parent.parent_email %>
</p>

<%= link_to 'Edit', edit_parent_path(@parent) %> |
<%= link_to 'Back', parents_path %>